
# Project information
site_name: 'nRF52832-MDK Documentation'
site_description: 'An Open Source, Micro Development Kit for IoT Applications'
site_author: 'Zelin'
site_url: 'https://makerdiary.github.io/nrf52832-mdk'


# Repository
repo_name: 'makerdiary/nrf52832-mdk'
repo_url: 'https://github.com/makerdiary/nrf52832-mdk'
edit_uri: ""


# Copyright
copyright: 'Copyright &copy; 2018 <a href="https://makerdiary.co">makerdiary.co</a>'

# Documentation and theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: 'images/favicon.ico'
  logo: 'images/logo.svg'

# Customization
extra:
  social:

    - type: slack
      link: https://join.slack.com/t/makerdiary/shared_invite/enQtMzIxNTA4MjkwMjc2LTM5MzcyNDhjYjI3YjEwOWE1YzM3YmE0YWEzNGNkNDU3NmE5M2M0MWYyM2QzZTFkNzQ2YjdmMWJlZjIwYmQwMDk
    - type: github-alt
      link: https://github.com/makerdiary
    - type: twitter
      link: https://twitter.com/makerdiary
    - type: facebook
      link: https://www.facebook.com/makerdiary
    - type: globe
      link: https://makerdiary.co

# Google Analytics
google_analytics:
  - 'UA-54344624-2'
  - 'auto'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


pages:
  - Overview: index.md
  - Getting Started: getting-started/index.md
  - nRF5 SDK: nrf5sdk/index.md
  - nRF5 SDK for Mesh: mesh/index.md
  - Arm Mbed OS: mbedos/index.md
  - Zephyr: zephyr/index.md
  - Mynewt: mynewt/index.md
  - Espruino: espruino/index.md
  - JerryScript: jerryscript/index.md
  - MicroPython: micropython/index.md
  - DAPLink: daplink/index.md
  - How to Buy: how-to-buy.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
  - 中文文档:
    - 简介: cn/index.md
    - 快速入门: cn/getting-started/index.md
    - nRF5 SDK: cn/nrf5sdk/index.md
    - nRF5 SDK for Mesh: cn/mesh/index.md
    - Arm Mbed OS: cn/mbedos/index.md
    - Zephyr: cn/zephyr/index.md
    - Mynewt: cn/mynewt/index.md
    - Espruino: cn/espruino/index.md
    - JerryScript: cn/jerryscript/index.md
    - MicroPython: cn/micropython/index.md
    - DAPLink: cn/daplink/index.md
    - 如何购买: cn/how-to-buy.md
    - 反馈&贡献: cn/CONTRIBUTING.md
    - 订阅: cn/about.md
    - License: cn/LICENSE.md

